digala = str(input('Qual seu nome completo? '))
maiusc = digala.upper()
minusc = digala.lower()
letras = len(digala.replace(' ',''))
primeiro = len(digala.split()[0])
print('O seu nome é: {}'.format(digala))
print('Seu nome em letras maiúsculas: {}.'.format(maiusc))
print('Seu nome em letras minúsculas: {}.'.format(minusc))
print('Seu nome completo tem {} letras.'.format(letras))
print('Seu primeiro nome tem {} letras.'.format(primeiro))